version: '3'
services:
  web:
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://myapp@postgres/myappdata
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: myapp
      POSTGRES_DB: myappdata